development: &default
  adapter: postgresql
  database: bacsignal_development
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: bacsignal_test
  min_messages: warning

cucumber:
  <<: *test